src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilePicture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\ResetPassType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use mysql_xdevapi\Exception;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        
        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    /**
     * @Route("/forgotten-pass", name="app-forgotten_password")
     */
    public function forgottenPass(Request $request, UserRepository $userRepository, MailerInterface $mailer, TokenGeneratorInterface $tokenGenerator, EntityManagerInterface $entityManager)
    {
        //crée le formulaire du reset de mot de passe
        $form = $this->createForm(ResetPassType::class);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $donnees = $form->getData();

            // on cherche si un utilisateur a cet email
            $user = $userRepository->findOneByEmail($donnees['email']);

            //si l'utilisteur n'existe pas
            if(!$user){
                // retourne un message flash
                $this->addFlash('danger', 'Cette adresse n\'existe pas');
                return $this->redirectToRoute('app_login');
            }

            $token = $tokenGenerator->generateToken();
            try {
                $user->setResetToken($token);
                $entityManager->persist($user);
                $entityManager->flush();
            }
            catch (\Doctrine\DBAL\Exception $e){
                $this->addFlash('warning', 'une erreur est survenue :'. $e->getMessage());
                return $this->redirectToRoute('app_login');
            }
            // on génère l'URL de renitialisation
            $url = $this->generateUrl('app_reset_password', [
                'token' => $token
            ], UrlGeneratorInterface::ABSOLUTE_URL);

            // envoi du message
            $message = (new TemplatedEmail())
                ->from(new Address('alternantreprise@outlook.fr', 'Contact Alternantreprise'))
                ->to($user->getEmail())
                ->subject('Rénitialiser votre mot de passe')
                ->htmlTemplate('emails/resetPass.html.twig')
                ->context([
                    'url' => $url
                ]);
            $mailer->send($message);
            $this->addFlash('message', 'une demande de mot de passe à été envoyer');

            return $this->redirect('login');
        }

        // on envoyer vers la page de demande de l'email
        return $this->render("security/forgotten_password.html.twig", ["emailForm" => $form->createView()]);
    }

    /**
     * @Route("/reset-pass/{token}", name="app_reset_password")
     */
    public function resetPassword($token, Request $request, UserPasswordHasherInterface $passwordHasher, UserRepository $userRepository, EntityManagerInterface $entityManager)
    {

        //on cherche l'utilisateur avec le token

        $user = $userRepository->findOneBy(['reset_token' => $token]);

        if (!$user) {
            $this->addFlash('danger', 'token inconnu');
            return $this->redirectToRoute('app_login');
        }

        if ($request->isMethod('POST')) {
            $user->setResetToken(null);

            $user->setPassword($passwordHasher->hashPassword($user, $request->request->get("password")));
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('message', 'le mot de passe modifié avec succès');


            return $this->redirectToRoute('app_login');
        }else {
            return $this->render('security/reset_password.html.twig', ['token' => $token]);
        }
    }
}

templates/security/forgotten_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublié{% endblock %}

{% block body %}

<link rel="stylesheet" href="{{ asset('assets/security.css') }}">
<section id="login">
  <div class="login-form">
    <h1 class="h3 mb-3 font-weight-normal">Mot de passe oublié</h1>
    {{ form(emailForm) }}
  </div>
</section>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
{% for message in app.flashes('message') %}
    <div class="alert alert-success" role="alert" style="">
        {{ message }}
    </div>
{% endfor %}
    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning" role="alert" style="width: 25vw; padding: 2%; border-radius: 15px; position: absolute; -webkit-box-shadow: 13px 5px 50px -1px rgba(0,0,0,0.17);
    box-shadow: 13px 5px 50px -1px rgba(0,0,0,0.17); text-align: center; left: 12%; ">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
        <div class="alert alert-danger" role="alert" style="width: 25vw; padding: 2%; border-radius: 15px; position: absolute; -webkit-box-shadow: 13px 5px 50px -1px rgba(0,0,0,0.17);
    box-shadow: 13px 5px 50px -1px rgba(0,0,0,0.17); text-align: center; left: 12%; ">
            {{ message }}
        </div>
    {% endfor %}
<link rel="stylesheet" href="{{ asset('assets/security.css') }}">
<section id="login">
    <div class="login-form">
    <form method="post">
    {% if error %}
        <div class="alert alert-danger">Erreur lors de la connexion, verifier vos identifiants de connexion</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}
        <h1 class="h3 mb-3 font-weight-normal">Connexion</h1>
        <label for="inputEmail">Email</label>
        <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control mt-3" autocomplete="email" required autofocus>
        <label for="inputPassword">Mot de passe</label>
        <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
        <div class="form-check">
            <label for="remember_me">Restez connecter</label>
            <input type="checkbox" name="_remember_me" id="remember_me" class="form-check-input" >
            <a href="{{ path('app-forgotten_password')}}" style="color:#0d131f; text-decoration: none; padding-left: 0;" class="form-check" >Mot de passe oublié</a>
        </div>

        <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}">
            <button class="btn btn-lg button mt-3" type="submit"> Connexion </button>
</form>
    </div>
</section>


    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}


{% endblock %}

templates/security/reset_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rénitialiser le mot de passe{% endblock %}

{% block body %}
    <link rel="stylesheet" href="{{ asset('assets/security.css') }}">
<section id="login">
    <div class="login-form">
        <h1>Entrez votre nouveau mot de passe </h1>
        <form method="post">
            <label for="pass" >Mot de passe </label>
            <input type="password" name="password" id="pass" class="form-control">
            <input type="hidden" name="token" value="{{ token }}">
            <button class="btn button mt-3"> Valider </button>
        </form>
    </div>
</section>

{% endblock %}